apiVersion: v1
kind: Template
metadata:
  annotations:
    fabric8.fhiresb/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/camel.svg
  labels: {}
  name: fhiresb
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      component: fhiresb
      container: java
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec: {}
  status:
    dockerImageRepository: ''
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      component: fhiresb
      container: java
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    resources: 
      limits:
        memory: 1Gi
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        - name: MAVEN_ARGS
          value: ${MAVEN_ARGS}
        - name: MAVEN_ARGS_APPEND
          value: ${MAVEN_ARGS_APPEND}
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:${BUILDER_VERSION}
          namespace: ${IMAGE_STREAM_NAMESPACE}
        incremental: true
      type: Source
    triggers:
    - github:
        secret: ${BUILD_SECRET}
      type: GitHub
    - generic:
        secret: ${BUILD_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      component: fhiresb
      container: java
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      component: fhiresb
      container: java
      deploymentconfig: ${APP_NAME}
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: fhiresb
          container: java
          deploymentconfig: ${APP_NAME}
          group: healthcare
          project: ${APP_NAME}
          provider: s2i
          version: ${APP_VERSION}
      spec:
        containers:
        - env:
          - name: A_MQ_SERVICE_NAME
            value: ${A_MQ_SERVICE_NAME}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: library/${APP_NAME}:latest
          name: ${APP_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - (curl -f 127.0.0.1:8778) >/dev/null 2>&1; test $? != 7
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      component: fhiresb
      container: java
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
      version: 1.0.0-SNAPSHOT
    name: fhiresb
  spec:
    ports:
    - name: netty
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      component: fhiresb
      container: java
      group: healthcare
      project: ${APP_NAME}
      provider: s2i
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: Application Name
  name: APP_NAME
  value: fhiresb
- description: Git repository, required
  name: GIT_REPO
  required: true
  value: https://github.com/yanxuehe/healthcaredemos2i.git
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  required: false
  value: projects/healthcaredemo/fhiresb/
- description: Git ref to build
  name: GIT_REF
  value: master
- description: Exposed Service name
  name: SERVICE_NAME
  value: fhiresb
- description: Builder version
  name: BUILDER_VERSION
  value: '1.0'
- description: Application version
  name: APP_VERSION
  value: 2.2.0.redhat-079
- description: Arguments passed to mvn in the build
  name: MAVEN_ARGS
  value: package -DskipTests -e
- description: Extra arguments passed to mvn, e.g. for multi-module builds
  name: MAVEN_ARGS_APPEND
- description: Maven build directory
  name: ARTIFACT_DIR
- description: The service name for AMQ
  name: A_MQ_SERVICE_NAME
  value: BROKER_AMQ_TCP
- description: Namespace in which the Fuse ImageStreams are installed. These ImageStreams
    are normally installed in the openshift namespace. You should only need to modify
    this if you've installed the ImageStreams in a different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: The secret needed to trigger a build
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: BUILD_SECRET
- description: Mirror site
  name: MAVEN_MIRROR_URL
  value: ''
